//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PARQUEOEntities : DbContext
    {
        public PARQUEOEntities()
            : base("name=PARQUEOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<TIQUETE_DETALLE> TIQUETE_DETALLE { get; set; }
        public virtual DbSet<TIQUETES_ENCABEZADO> TIQUETES_ENCABEZADO { get; set; }
        public virtual DbSet<VEHICULO> VEHICULOS { get; set; }
    
        public virtual int GenereaTiquete(string uSUARIO, Nullable<int> iDcliente, string numeroPlaca, ObjectParameter mensaje)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var iDclienteParameter = iDcliente.HasValue ?
                new ObjectParameter("IDcliente", iDcliente) :
                new ObjectParameter("IDcliente", typeof(int));
    
            var numeroPlacaParameter = numeroPlaca != null ?
                new ObjectParameter("NumeroPlaca", numeroPlaca) :
                new ObjectParameter("NumeroPlaca", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenereaTiquete", uSUARIOParameter, iDclienteParameter, numeroPlacaParameter, mensaje);
        }
    }
}
