//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIQUETE_DETALLE
    {
        public int IDtiquete { get; set; }
        public string NumeroPlaca { get; set; }
        public int IDcliente { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIQUETES_ENCABEZADO TIQUETES_ENCABEZADO { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
